Explain all commands needed for one-off container management
Scalingo/documentation pull request #1386
Opened 2021-09-08 13:05 UTC by curzolapierre

Thanks @vonox7

2021-09-08 13:09 UTC, Soulou requested changes
The right command for this is actually to use `scalingo ps` listing all containers, which command, since when they are running etc.

2021-09-08 13:55 UTC, EtienneM commented on _posts/platform/app/2000-01-01-tasks.md
> +## Stop a Detached One-Off
From what I remember, it stops any one-off

```suggestion
## Stop a One-Off
```

2021-09-08 15:47 UTC, vonox7 commented on _posts/platform/app/2000-01-01-tasks.md
> +scalingo --app my-app stats
```suggestion
scalingo --app my-app ps
```

2021-09-09 07:30 UTC, EtienneM commented on _posts/platform/app/2000-01-01-tasks.md
> +you can use the `stats` command.
```suggestion
you can use the `ps` command.
```

2021-09-15 12:01 UTC, Soulou approved these changes

2021-09-15 12:31 UTC, merged