Clarify relation PID <-> thread
Scalingo/documentation pull request #1466
Opened 2021-11-24 11:17 UTC by cyrille-sg

2021-11-24 11:34 UTC, btrd commented on _posts/platform/internals/2000-01-01-container-sizes.md
> +As a note, each new process will require a PID and inside each process, each thread will neeed one too.
```suggestion
As a note, each new process will require a PID and inside each process, each thread will need one too.
```

2021-11-24 15:24 UTC, EtienneM requested changes

2021-11-24 15:24 UTC, EtienneM commented on _posts/platform/internals/2000-01-01-container-sizes.md
> +As a note, each new process will require a PID and inside each process, each thread will neeed one too.
I wouldn't use the future tense here:

```suggestion
As a note, each new process requires a PID. And inside each process, each thread needs one too.
```

2021-11-29 09:27 UTC, btrd approved these changes

2021-11-30 10:52 UTC, EtienneM approved these changes

2021-11-30 10:52 UTC, merged