feat(timescaledb): create a TimescaleDB documentation
Scalingo/documentation pull request #1520
Opened 2022-01-21 16:49 UTC by curzolapierre

Contains:
- TimescaleDB extension introduction
- Downsampling
- Data retention

Fix #1512

2022-01-21 17:00 UTC, Soulou requested changes

2022-01-21 17:00 UTC, Soulou commented on _posts/databases/postgresql/TimescaleDB/2000-01-01-downsample.md
> +So we can use a downsample logic which will reduce the datas older than one week,
```suggestion
So we can use a downsampling logic which will reduce the datas older than one week,
```

2022-01-21 17:00 UTC, Soulou commented
`downsample` is a verb, not a noun ;-)

2022-01-25 10:10 UTC, EtienneM requested changes

2022-01-25 10:10 UTC, EtienneM commented on _posts/databases/postgresql/TimescaleDB/2000-01-01-downsample.md
> +```SQL
I don't know if it matters for Jekyll but I would write a lower case `SQL`.

2022-01-25 10:10 UTC, EtienneM commented on _posts/databases/postgresql/TimescaleDB/2000-01-01-downsample.md
> +This script invoke the created procedure `downsample_conditions` to apply it for
```suggestion
This script invokes the created procedure `downsample_conditions` to apply it for
```

2022-01-25 10:10 UTC, EtienneM commented on _posts/databases/postgresql/TimescaleDB/2000-01-01-intro.md
> +than the Community edition. You can check the comparison between both edition,
By being an external reader, I don't understand what you are talking about with this "Community edition". It seems it comes out of nowhere. Maybe it's less odd to say that the list of TimescaleDB functions introduced by enabling TimescaleDB on a PostgreSQL database is here (https://docs.timescale.com/api/latest/). From this list, the functions labelled as `Community` are not available on Scalingo.

2022-01-31 13:50 UTC, EtienneM requested changes
Thanks a lot for these pages. I didn't expect it to be that simple. I'm happy \o/

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-intro.md
> +on their documentation: [https://docs.timescale.com/api/latest](https://docs.timescale.com/api/latest).
I find it ugly to have the URL displayed, I prefer a link with a meaningful text
```suggestion
TimescaleDB is a PostgreSQL extension for the support of time-series data.
This extension adds several features and functions. You can find more information
on the [official documentation](https://docs.timescale.com/api/latest).
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-intro.md
> +place, we present some of them here.
I don't like this paragraph. I find it too deceptive. I don't see what it adds, I would remove it
```suggestion
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-intro.md
> +are not available on the platform.
Maybe this introduction page should talk about the two other pages created, and link to them?

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +nav: Downsampling
You don't need a nav if it's the same as the title:
```suggestion
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +Downsampling data allows to reduce the amount of data by simplifying the old values.
Simplification suggestion:

```suggestion
The downsampling reduces the amount of data by simplifying the old values.
```

I don't like the word "simplifying". I don't understand what it means

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +value. This is a use case where a table is composed of raw datas.
data is still uncountable. Do you have a dictionary installed in the text editor you use to write doc? It should highlight that `datas` does not exist

```suggestion
value. This is a use case where a table is composed of raw data.
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +Now we want to decrease the database size. We don't need to have data by the
nitpick: I'm not sure about the purpose of the word `Now` here. From my point of view it does not add any information.

```suggestion
We want to decrease the database size. We don't need to have data by the
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +and only store the average by hour.
We rarely use the future tense in documentation pages:
```suggestion
So we can use a downsampling logic which reduces the data older than one week,
and only stores the average by hour.
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +For the following table:
Not sure about this one

```suggestion
For the following data:
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +The procedure bellow contains the logic to downsample the table `conditions`
I didn't know but the word `bellow` exists and means "mugir" or "beugler" xD

```suggestion
The procedure below contains the logic to downsample the table `conditions`
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +Bellow an example of a logic of downsampling. It is based on TimescaleDB documentation.
If it's based on the official doc, please make `TimescaleDB documentation` a link to the said page

```suggestion
Below an example of a logic of downsampling. It is based on TimescaleDB documentation.
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +To do so, add a `cron.json` file at the root of your application’s source code,
nitpick: not sure `To do so` adds anything here. And it really sounds like a French translation to my hears. I might be wrong:
```suggestion
Add a `cron.json` file at the root of your application’s source code,
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-data-retention.md
> +nav: Data Retention
Duplicate of the title, not needed 
```suggestion
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-data-retention.md
> +Below an example of a retention policy which apply on __all__ hypertables.
```suggestion
Below an example of a retention policy which applies on __all__ hypertables.
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-data-retention.md
> +`WHERE` clause in the `PERFORM` query.
I don't understand this sentence

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-data-retention.md
> +You can schedule the execution of the previous procedure by using
```suggestion
You can schedule the execution of the previous procedure by using the
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-downsampling.md
> +You can schedule the execution of the previous procedure by using
```suggestion
You can schedule the execution of the previous procedure by using the
```

2022-01-31 13:50 UTC, EtienneM commented on _posts/databases/postgresql/timescaledb/2000-01-01-data-retention.md
> +command that invoke a SQL script called `data_retention_procedure.sql`.
```suggestion
command that invokes a SQL script called `data_retention_procedure.sql`.
```

2022-02-14 13:14 UTC, EtienneM approved these changes

2022-02-14 14:56 UTC, EtienneM commented
@curzolapierre we don't want auto merge on this PR. We don't want our documentation to talk about TimescaleDB whereas the product is not ready yet. After Léo approves this PR, we should wait for the end of the development of this product to merge the PR

2022-02-22 08:39 UTC, Soulou approved these changes
LGTM to merge after product release.

2022-02-24 10:22 UTC, EtienneM approved these changes

2022-02-24 10:22 UTC, merged