docs(log-drains): update appsignal and syslog tcp+tls examples and parameters
Scalingo/documentation pull request #1785
Opened 2022-10-24 12:20 UTC by ipfaze

This PR updates documentation about the new AppSignal compatibility and the token parameter for syslog (tcp+tls)
FIX #1779

2022-10-25 09:02 UTC, curzolapierre requested changes
Could you update the page metadata too, especially the `modified_at` field.

Otherwise LGTM, but this PR should be merge after the API changes

2022-10-25 09:03 UTC, curzolapierre commented on src/_posts/platform/app/2000-01-01-log-drain.md
> +* `token`: API key of your application
To avoid any confusion.
```suggestion
* `token`: Appsignal's API key
```

2022-10-25 14:02 UTC, ipfaze commented
Token's description and metadata `modified_at` are up to date

2022-10-26 10:11 UTC, curzolapierre approved these changes
LGTM

2022-11-02 18:52 UTC, merged