Be explicit about business hours
Scalingo/documentation pull request #1811
Opened 2022-11-14 15:05 UTC by btrd

Ping @aurelien-reeves-scalingo

2022-11-14 15:06 UTC, yanjost commented
Why the change ?

2022-11-14 15:07 UTC, btrd commented
It wasn't clear what our business hours were

See https://scalingo.slack.com/archives/C01U5K16FM2/p1668436076225989?thread_ts=1668434669.778539&cid=C01U5K16FM2

2022-11-14 15:46 UTC, aurelien-reeves-scalingo commented on src/_posts/security/procedures/2000-01-01-external-testing.md
> +- The test should only be run during business hours (9AM to 12AM - 2PM to 6PM)
I would indicate the timezone.
Or UTC times

2022-11-22 10:47 UTC, btrd commented on src/_posts/security/procedures/2000-01-01-external-testing.md
> +- The test should only be run during business hours (9AM to 12AM - 2PM to 6PM)
```suggestion
- The test should only be run during business hours - 08:00 to 11:00 and 13:00 to 15:00 (UTC)
```

2022-11-22 11:54 UTC, yanjost requested changes

2022-11-22 11:54 UTC, yanjost commented on src/_posts/security/procedures/2000-01-01-external-testing.md
> +- The test should only be run during business hours - 08:00 to 11:00 and 13:00 to 15:00 (UTC)
```suggestion
- The test should only be run during business hours - 08:00 to 11:00 and 13:00 to 15:00 (UTC+1, Europe/Paris timezone)
```

2022-11-22 13:30 UTC, aurelien-reeves-scalingo requested changes

2022-11-22 13:32 UTC, btrd commented on src/_posts/security/procedures/2000-01-01-external-testing.md
> +{% include security_testing_warning.md %}
```suggestion
```

2022-11-23 08:55 UTC, btrd commented on src/_posts/security/procedures/2000-01-01-external-testing.md
> +{% include security_testing_warning.md %}
It's really not clear on Github interface, but this is adding a end of file new line

2022-11-23 11:23 UTC, merged