Add SSB-2023-002
Scalingo/documentation pull request #2203
Opened 2023-07-25 16:07 UTC by yanjost

2023-07-25 16:09 UTC, Soulou approved these changes
I like it

2023-07-26 07:55 UTC, LouisaEA requested changes

2023-07-26 07:55 UTC, LouisaEA commented on src/_posts/security/bulletins/2023-07-24-SSB-2023-002.md
"score between 8.7 and 10 ." > "score between 8.7 and 10." (remove space)

"This is not in any way a vulnerability " > "This is not, in any way, a vulnerability "

"and due to is severity" > "and due to its severity"

"we have decided to publish a security bulletin." > "we have decided to publish a Security Bulletin."

"metabase instance" > "Metabase instance"

"the potentially impacted customers have been informed with an individual message." > Informed by who? Scalingo or Metabase? If we contacted them, write "We have contacted the potentially impacted customers with an individual message."

"reported this blog post on Metabase's blog :" > "reported this blog post on Metabase's blog:" (remove space)

"our customer would immediately benefit" >  "our customers would immediately benefit"

Please use the paragraph below:
| 2023-07-21 15:00 | Internal report | | 2023-07-21 15:00 | Developer starts to work on fix | |2023-07-21 15:15 | Engineer starts to analyse the vulnerability |2023-07-21 16:00 | Internal Metabase instances are shutdown | 2023-07-21 16:45 | Metabase buildpack fixed and tested |2023-07-21 17:00 | Internal Metabase instances fixed and restarted |2023-07-26 | Publishing this Bulletin and information to our users

2023-07-26 07:57 UTC, yanjost commented on src/_posts/security/bulletins/2023-07-24-SSB-2023-002.md
About the space : it was intentional because I found it strange to write "between 8.7 and 10."

2023-07-26 09:04 UTC, merged