feat(mysql): add one command script to migrate on MySQL 8
Scalingo/documentation pull request #2420
Opened 2023-12-28 17:12 UTC by curzolapierre

2023-12-29 09:01 UTC, ipfaze requested changes
Some suggestions, overall LGTM :+1:

2023-12-29 09:05 UTC, yohann-bacha requested changes
Some feedback on the english, but overall if the script works, that's great

2023-12-29 09:05 UTC, yohann-bacha commented on src/_posts/databases/mysql/2000-01-01-mysql-8-prerequisites.md
> +As always, we highly recommend to make a backup before executing the script.
**suggestion:** 

```suggestion
The following script creates two procedures, one for each previous actions. As always, we highly recommend to make a backup before executing the script.
```

2023-12-29 09:09 UTC, yohann-bacha commented on src/_posts/databases/mysql/2000-01-01-mysql-8-prerequisites.md
> +As always, we highly recommend to make a backup before executing the script.
In fact, I prefer Mederic's suggestion on the warning block

2023-12-29 09:41 UTC, ipfaze approved these changes
LGTM :+1:

2023-12-29 10:36 UTC, yohann-bacha requested changes
One last nitpick but after this LGTM

2023-12-29 10:36 UTC, yohann-bacha commented on src/_posts/databases/mysql/2000-01-01-mysql-8-prerequisites.md
> +In fact, the script create two procedures, one for each previous actions.
**suggestion:** I don't know if the "In fact" is really necessary here 

```suggestion
The script creates two procedures, one for each previous actions.
```

2024-01-03 09:12 UTC, yohann-bacha requested changes

2024-01-03 09:12 UTC, yohann-bacha commented on src/_posts/databases/mysql/2000-01-01-mysql-8-prerequisites.md
> +    SET @prepstmt = CONCAT('ALTER TABLE ',v_table,' ADD COLUMN id INT AUTO_INCREMENT NOT NULL PRIMARY KEY FIRST;');
**issue:** this column name is too common. for the record, I have a table that have a column named `id` but not primary. This query fails to execute.

```suggestion
    SET @prepstmt = CONCAT('ALTER TABLE ',v_table,' ADD COLUMN generated_pk INT AUTO_INCREMENT NOT NULL PRIMARY KEY FIRST;');
```

2024-01-08 14:45 UTC, yohann-bacha approved these changes

2024-01-08 14:45 UTC, merged