[STORY-525] Add documentation for PostgreSQL 15
Scalingo/documentation pull request #2624
Opened 2024-05-27 12:55 UTC by leo-scalingo

2024-05-27 13:16 UTC, Frzk requested changes
praise: Thanks for updating the doc <3

I suggest to also update the sentence with the default version. Otherwise, LGTM :)

2024-05-27 13:16 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-overview.md
>  application.
```suggestion
The default version when attaching a PostgreSQL® addon to your
application is **14.12.0-1**.
```

2024-05-27 13:23 UTC, Frzk approved these changes

2024-06-03 15:10 UTC, leo-scalingo commented on src/_posts/databases/postgresql/2000-01-01-pgvector.md
> +__Example: have a look at [OpenAI Embeddings Documentation](https://platform.openai.com/docs/guides/embeddings))__
```suggestion
__Example: have a look at [OpenAI Embeddings Documentation](https://platform.openai.com/docs/guides/embeddings)__
```

2024-06-14 08:26 UTC, merged