feat: Add a section about daphne in the django getting started
Scalingo/documentation pull request #2748
Opened 2024-08-14 15:55 UTC by SCedricThomas

fix #2474

2024-08-15 07:35 UTC, EtienneM requested changes
Did you tested on the Django sample that it works?

2024-08-15 07:35 UTC, EtienneM commented on src/_posts/languages/python/django/2000-01-01-start.md
> +It is also possible to use Daphne as an ASGI server.
suggestion: maybe add a link to the Daphne homepage?

2024-08-15 07:35 UTC, EtienneM commented on src/_posts/languages/python/django/2000-01-01-start.md
> +Here an example start.sh script to use Daphne:
issue: 
- the sentence is not really well written. It's really hard to understand. I don't think it's a very good English.
- it's kind of hard to understand you refer to the `start.sh` script from the previous section
- I am not sure it should be a different paragraph than the previous one.
question: How is it possible to install the `daphne` CLI?

```suggestion
It is also possible to use Daphne as an ASGI server. You can update the `bin/start.sh` script described in the previous section to use Daphne to start the application:
```

2024-08-15 07:35 UTC, EtienneM commented on src/_posts/languages/python/django/2000-01-01-start.md
> +daphne -b 0.0.0.0 -p $PORT myapp.asgi:application --proxy-headers
question: are there long options to replace `-b` and `-p`?

2024-08-22 06:33 UTC, SCedricThomas commented
Here is an example of the django sample using Daphne as AGSI server: https://sample.osc-fr1.scalingo.io/

2024-08-22 07:13 UTC, EtienneM reviewed
Sorry, just one thing I forgot about in the previous review. Can you update the front matter to update the  last modification date of the page? Then it LGTM

2024-08-22 07:14 UTC, SCedricThomas commented
Oh right :face_holding_back_tears:

2024-08-22 07:35 UTC, EtienneM approved these changes

2024-08-22 07:35 UTC, merged