Update 2000-01-01-detecting-https-requests.md
Scalingo/documentation pull request #2757
Opened 2024-08-22 15:56 UTC by sc-david-voisin

Fix this error:
```sh
./main.go:11:10: invalid operation: req.Header.Get("X-Forwarded-Proto" == "https") || req.URL.Scheme == "https" (mismatched types string and untyped bool)
./main.go:11:25: cannot use "X-Forwarded-Proto" == "https" (untyped bool constant false) as string value in argument to req.Header.Get
```

2024-08-22 16:01 UTC, EtienneM approved these changes

2024-08-23 07:24 UTC, mcimbaro requested changes
Please update the `updated_at` field

2024-08-23 07:40 UTC, sc-david-voisin commented
> Please update the `updated_at` field

To be sure, do you mean the `modified_at` in the header of the page ?

2024-08-23 07:57 UTC, mcimbaro commented
> > Please update the `updated_at` field
> 
> To be sure, do you mean the `modified_at` in the header of the page ?

Yes, thanks!

2024-08-23 07:57 UTC, mcimbaro approved these changes
Nice catch

**Suggestion :** Update the PR title before merging?

2024-08-23 08:41 UTC, merged