[Node.js] Confusion about how to prune devDependencies
Scalingo/documentation pull request #2841
Opened 2024-10-11 08:42 UTC by TheoPouletSouchard

See https://github.com/Scalingo/documentation/issues/2839

2024-10-11 08:43 UTC, TheoPouletSouchard commented
@EtienneM I tried something with a table, it might be easier to read, WDYT ? (i can rollback to old way if you think it was better before)

2024-10-11 10:14 UTC, EtienneM requested changes
I like the idea of a table, but the CLI column is too much. It does not render well:

![image](https://github.com/user-attachments/assets/52b3b9ac-78eb-4cf6-b1dc-42ade4a16b21)

Maybe remove this column, add a column "Value" and add a line after the table like:

```
scalingo --app my-app env-set variable=value
```
or something like that?

2024-10-11 12:32 UTC, TheoPouletSouchard commented
> I like the idea of a table, but the CLI column is too much. It does not render well:
> 
> ![image](https://private-user-images.githubusercontent.com/1567651/375717165-52b3b9ac-78eb-4cf6-b1dc-42ade4a16b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDE5NTEsIm5iZiI6MTcyODY0MTY1MSwicGF0aCI6Ii8xNTY3NjUxLzM3NTcxNzE2NS01MmIzYjlhYy03OGViLTRjZjYtYjFkYy00MmFkZTRhMTZiMjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTAxNDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTljYzY2ZDQ4NzUwZmYxYTk1N2IyNzkwM2ZjMTM3ODU1NDJlZGE3OTRkYmNmZGFjNWNmNzczNTAxZDgxZTA4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.KGAzRDfil14wOv3o88Y0AS_CH8j0TpLo7jPyqsLopaw)
> 
> Maybe remove this column, add a column "Value" and add a line after the table like:
> 
> ```
> scalingo --app my-app env-set variable=value
> ```
> 
> or something like that?

Uhm i see what you mean. I'm wondering: as the values just need to be set and can be any string to work, the "value" column is useless, isn't it ? 

It might be better to:
- Remove the CLI column-
- Add the CLI line under the table (as you suggested) 
- Add a small text to say "the values can be anything as long as they are set to be valid" (written in a better way)

WDYT?

2024-10-21 09:32 UTC, Frzk commented
Hello @TheoPouletSouchard

Thanks a lot for this PR <3

> Uhm i see what you mean. I'm wondering: as the values just need to be set and can be any string to work, the "value" column is useless, isn't it ?

- For `NPM_CONFIG_PRODUCTION`, it seems the value MUST be either `true` or `false` (See https://github.com/Scalingo/nodejs-buildpack/blob/a2a95190bcc7482f61d3dc7b4cc853d25785a117/lib/environment.sh#L61)
- For `YARN_PRODUCTION`, it seems it MUST be set to `true` to be effective. (see https://github.com/Scalingo/nodejs-buildpack/blob/a2a95190bcc7482f61d3dc7b4cc853d25785a117/lib/failure.sh#L371)
- For `YARN2_SKIP_PRUNING`, it seems it MUST be set to `true` to be effective. (see https://github.com/Scalingo/nodejs-buildpack/blob/a2a95190bcc7482f61d3dc7b4cc853d25785a117/lib/dependencies.sh#L181)

While I strongly agree that the presence/absence of the environment variable should be enough, it seems it's not the case.

Consequently, I suggest to replace the CLI column of the table with a "Value" column and put an example below.

2024-10-28 08:25 UTC, EtienneM requested changes

2024-10-28 08:25 UTC, EtienneM commented on src/_posts/languages/nodejs/2000-01-01-start.md
> +| npm             | Any     | `NPM_CONFIG_PRODUCTION` | `true`  or `false` |
issue: well, from the code sent by François, the value to skip the pruning should be `true`, shouldn't it?

```suggestion
| npm             | Any     | `NPM_CONFIG_PRODUCTION` | `true`  |
```

2024-10-28 08:49 UTC, EtienneM approved these changes
Thanks a lot!! :rocket:

2024-10-28 08:49 UTC, merged