feat(db): Add new db dashboard documentation
Scalingo/documentation pull request #2847
Opened 2024-10-21 14:23 UTC by baptmaury

Wording is based on https://github.com/Scalingo/documentation/pull/2846

2024-10-22 09:00 UTC, Anouchka-M requested changes

2024-10-22 09:40 UTC, Frzk requested changes
I've made a bunch of suggestions.
IMHO, some are required. Some others may be more arguable, I'll let you decide.

Nice work on the dashboard <3

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-accessing.md
>  6. The database is now available using the corresponding [connection URI]({% post_url databases/postgresql/2000-01-01-connecting %})
```suggestion
4. In the Settings submenu, select **Internet Access**
5. Locate the **Internet Accessibility** block
6. Click the **Enable** button
7. The database is now available using the corresponding [connection URI]({% post_url databases/postgresql/2000-01-01-connecting %})
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-backing-up.md
> +6. Click the **Update** button to validate
```suggestion
4. Click the **Schedule** button
5. Make sure to check the **I want to enable scheduled backups** checkbox
6. Pick an hour (**timezone is UTC**)
7. Validate by clicking the **Update** button
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-connecting.md
>  {% include mdl_img.html %}
I'd remove the screenshot and just put that as the last instruction:
```suggestion
5. Click the **Enable** button
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +4. To launch the upgrade, click the **Upgrade to ...** button
```suggestion
2. Select the **Settings** tab
3. In the **Settings** submenu, select the **General** tab
4. Locate the **Database Version** block
5. If an upgrade is available, a button allows you to trigger the upgrade
6. Click the button to launch the upgrade process
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +4. The list of available users is displayed under the **User Management**
```suggestion
2. Click the **Settings** tab
3. In the **Settings** submenu, select **Users**
4. The list of available users is displayed in the **User Management** block
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +3. In the **Settings** menu, select **Users**
```suggestion
2. Click the **Settings** tab
3. In the **Settings** submenu, select **Users**
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +6. Confirm the deletion by typing the name of the user in the popup window
```suggestion
2. Click the **Settings** tab
3. In the **Settings** submenu, select **Users**
4. Locate the user you want to remove
5. Click the **…** button next to the user and select **Delete user** from the popup menu
6. In the popup window, confirm the deletion by typing the name of the user
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +### Show the enabled extensions
```suggestion
### Viewing Enabled Extensions
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +5. The list of enabled extensions will appear in small pills
```suggestion
2. Click the **Settings** tab
3. In the **Settings** submenu, select **Configuration**
4. Locate the **PostgreSQL Extensions** block
5. The list of enabled extensions is displayed here
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-restoring.md
> +5. Click the **Confirm** button
```suggestion
3. Click the **Start a PiTR** button
4. Pick a date and time (**timezone is UTC**)
5. Make sure to check the **I understand that this action will permanently delete existing data and cannot be cancelled or undone once started.** checkbox
6. Validate by clicking the **Confirm** button
```

2024-10-22 09:40 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-accessing.md
> +4. In the **Settings** submenu, select **Internet Access** (settings/networking)
```suggestion
4. In the **Settings** submenu, select **Internet Access**
```

2024-10-22 10:41 UTC, Frzk requested changes
Almost there :smile_cat:

2024-10-22 10:41 UTC, Frzk commented on src/_posts/databases/mysql/2000-01-01-accessing.md
> +4. In the Settings submenu, select **Internet Access**
```suggestion
4. In the **Settings** submenu, select **Internet Access**
```

2024-10-22 10:41 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-connecting.md
> +3. In the Settings submenu, select **Internet Access**
```suggestion
3. In the **Settings** submenu, select **Internet Access**
```

2024-10-22 10:41 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
>  7. Click the **Finish** button
```suggestion
4. Locate the **Addons** block
5. Click the **"&#8230;"** button
6. From the dropdown menu, select **Change plan**
7. Select the new plan
8. Validate by clicking the **Finish** button
```

2024-10-22 10:41 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +6. Validate by clicking the **Add this user** button
```suggestion
   - (optional) To allow the new user to have writings abilities, make
     sure to check the **Write (optional)** checkbox
5. Validate by clicking the **Add this user** button
```

2024-10-22 10:41 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +Protected users password cannot be updated
```suggestion
Protected users password cannot be updated.
```

2024-10-22 10:41 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +Protected users cannot be deleted
```suggestion
Protected users cannot be deleted.
```

2024-10-22 10:41 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +5. The list of enabled extensions is displayed here
```suggestion
4.  The list of enabled extensions is displayed in the **PostgreSQL Extensions** block
```

2024-10-22 10:41 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +7. Validate by clicking the **Confirm** button
```suggestion
5. Click the **&#8230;** button next to the user
6. From the popup menu, select **Delete user**
7. In the popup window, confirm the deletion by typing the name of the user
8. Validate by clicking the **Confirm** button
```

2024-10-22 12:17 UTC, baptmaury commented on src/_posts/databases/postgresql/2000-01-01-accessing.md
>  6. The database is now available using the corresponding [connection URI]({% post_url databases/postgresql/2000-01-01-connecting %})
already implemented

2024-10-22 12:17 UTC, baptmaury commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +4. The list of available users is displayed under the **User Management**
already implemented

2024-10-22 12:18 UTC, baptmaury commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +3. In the **Settings** menu, select **Users**
already implemented

2024-10-22 12:18 UTC, baptmaury commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +6. Confirm the deletion by typing the name of the user in the popup window
already implemented

2024-10-22 12:19 UTC, baptmaury commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +5. The list of enabled extensions will appear in small pills
already implemented

2024-10-22 13:21 UTC, Frzk requested changes

2024-10-22 13:21 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +8. Validate by clicking the **Finish** button
Sorry this one is my fault :-(
```suggestion
8. Click the **Finish** button
```

2024-10-22 13:21 UTC, Frzk commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +{% endnote %}
```suggestion
{% note %}
A secure password is generated automatically and shown in a popup window after the user creation.
You will be able to view and copy it only once.
{% endnote %}
```

2024-10-23 08:00 UTC, baptmaury commented on src/_posts/databases/postgresql/2000-01-01-managing.md
> +{% endnote %}
Implemented

2024-10-23 09:36 UTC, Frzk approved these changes
LGTM :tada: 
Well done :)

2024-10-31 11:18 UTC, Anouchka-M approved these changes

2024-10-31 11:18 UTC, merged