[ICY-468] Update 2000-01-01-secnumcloud.md: EN improvement + ID control step addition
Scalingo/documentation pull request #2895
Opened 2024-12-02 13:19 UTC by SC-Jerome-S

Update 2000-01-01-secnumcloud.md: EN improvement + ID control step addition Was discussed with support team in November 2024 to make external process clearer.

2025-01-09 15:38 UTC, yanjost requested changes

2025-01-09 15:38 UTC, yanjost commented on src/_posts/security/procedures/2000-01-01-secnumcloud.md
> +You may need to prepare the ID card or passport (or use official tools like [France Identité](https://france-identite.gouv.fr/justificatif/)) of the new app owner.
Too vague. Don't use terms like "you may" or too many "ors". The procedure has to be very clear.

2025-01-09 15:38 UTC, yanjost commented on src/_posts/security/procedures/2000-01-01-secnumcloud.md
> +- The user must act as an employee of a company, using his/her company email (domain verification)
Be more explicit with "domain verification"

2025-01-16 14:40 UTC, SC-Jerome-S reviewed
@yanjost

2025-01-16 14:40 UTC, SC-Jerome-S commented on src/_posts/security/procedures/2000-01-01-secnumcloud.md
> +You may need to prepare the ID card or passport (or use official tools like [France Identité](https://france-identite.gouv.fr/justificatif/)) of the new app owner.
```suggestion
Prepare the Identity Document of the new app owner or use official tools like [France Identité](https://france-identite.gouv.fr/justificatif/)).
```

2025-01-16 14:40 UTC, SC-Jerome-S commented on src/_posts/security/procedures/2000-01-01-secnumcloud.md
> +- The user must act as an employee of a company, using his/her company email (domain verification)
```suggestion
- The user must act as an employee of a company, using his/her company email (domain verification ensures that your organization owns or controls the specified domain, allowing you to authenticate and secure email communications sent on behalf of your company)
```

2025-01-16 14:40 UTC, SC-Jerome-S commented on src/_posts/security/procedures/2000-01-01-secnumcloud.md
> +- The user must act as an employee of a company, using his/her company email (domain verification)
Like this ?

2025-02-10 14:50 UTC, yanjost commented on src/_posts/security/procedures/2000-01-01-secnumcloud.md
> +- The user must act as an employee of a company, using his/her company email (domain verification)
Why change the subject in the middle of the sentence? I would say
```suggestion
- The user must act as an employee of a company, using his/her company email (domain verification  ensures that the organization controls the specified domain, allowing us to authenticate email communications sent on behalf of the company)
```

2025-02-10 14:50 UTC, yanjost commented on src/_posts/security/procedures/2000-01-01-secnumcloud.md
> +You may need to prepare the ID card or passport (or use official tools like [France Identité](https://france-identite.gouv.fr/justificatif/)) of the new app owner.
What does "prepare" mean in this context? You mean "send" or "share"?

2025-02-10 14:52 UTC, yanjost requested changes
Please apply requested changes

2025-02-12 09:00 UTC, SC-Jerome-S commented on src/_posts/security/procedures/2000-01-01-secnumcloud.md
> +You may need to prepare the ID card or passport (or use official tools like [France Identité](https://france-identite.gouv.fr/justificatif/)) of the new app owner.
Agree about the "may", disagree about the "or"
I'm proposing a change

2025-02-12 10:33 UTC, SC-Jerome-S reviewed
Included the review recommendations

2025-02-13 17:38 UTC, yanjost approved these changes
LGTM

2025-02-14 10:44 UTC, merged