docs(php) - sending emails
Scalingo/documentation pull request #2903
Opened 2024-12-10 10:17 UTC by sc-zenokerr

Fixes #1085

This PR adds some basic information about sending emails from PHP, and an example using Brevo.

2024-12-10 10:26 UTC, EtienneM reviewed
Did you tested this code? If yes and you confirm it's working, then LGTM :)

2024-12-10 10:26 UTC, EtienneM commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +For sending emails from your php application you will need to send via an external smtp server.
```suggestion
For sending emails from your PHP application you will need to send via an external SMTP server. 
```

2024-12-10 16:18 UTC, Frzk requested changes
I'm not sure whether documenting a specific framework is really what we want to do (because maintenance, etc.)

Also, we should probably advise to use Composer to install the dependency, like so:
```bash
composer require phpmailer/phpmailer
```

2024-12-10 16:18 UTC, Frzk commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +    $mail->Password   = 'YOUR_BREVO_PASSWORD';
```suggestion
    $mail->Username   = getenv('BREVO_USERNAME');
    $mail->Password   = getenv('BREVO_PASSWORD');
```

2024-12-11 14:30 UTC, sc-zenokerr commented
@Frzk I actually agree.. do you think it would be ok to remove the sample?
It is difficult to test in anycase (without us having an account with Brevo)

2024-12-17 08:40 UTC, aurelien-reeves-scalingo commented
I agree with @Frzk 

Why Brevo specifically?
Specially as this is just regular SMTP here. There is no need to limit the case to Brevo IMO

2025-07-09 07:18 UTC, Frzk commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +    $mail->Port       = 587;
```suggestion
    $mail->Host       = getenv('SMTP_SERVER');
    $mail->SMTPAuth   = true;
    $mail->Username   = getenv('SMTP_USERNAME');
    $mail->Password   = getenv('SMTP_PASSWORD');
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->Port       = getenv('SMTP_PORT');
```

2025-07-09 07:19 UTC, Frzk commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +    $mail->AltBody = 'This is a test email sent using PHPMailer with Brevo SMTP.';
```suggestion
    $mail->Subject = 'Test Email from PHPMailer';
    $mail->Body    = '<p>This is a test email sent using PHPMailer from my app hosted on Scalingo.</p>';
    $mail->AltBody = 'This is a test email sent using PHPMailer from my app hosted on Scalingo.';
```

2025-07-09 07:19 UTC, Frzk commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +### Example using PHPMailer via Brevo
```suggestion
### Example Using PHPMailer
```

2025-07-09 08:00 UTC, aurelien-reeves-scalingo approved these changes

2025-07-09 08:00 UTC, aurelien-reeves-scalingo commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +Several options are listed on our [dedicated section]({% post_url platform/app/2000-01-01-sending-emails %}).
(Neat pick) to avoid repetitions:
```suggestion
For sending emails from your PHP application you will need to use an external SMTP server. 
Several options are listed on our [dedicated section]({% post_url platform/app/2000-01-01-sending-emails %}).
```

2025-07-09 08:00 UTC, aurelien-reeves-scalingo commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +You can use a mailing library such as [PHPMailer](https://github.com/PHPMailer/PHPMailer) (or equivalent) to send from your PHP application, via an external SMTP server.
(neat pick) wording
```suggestion
You can use a mailing library such as [PHPMailer](https://github.com/PHPMailer/PHPMailer) (or equivalent) to send emails from your PHP application via an external SMTP server.
```

2025-07-09 08:18 UTC, sc-zenokerr commented
@Frzk 
Thanks for re-animating this PR.
Is this ok for you now?
I can't merge it as there is your review blocking it. Can you approve (or request changes) please ? :) 
Thanks

2025-07-09 08:23 UTC, aurelien-reeves-scalingo commented
> I'm not sure whether documenting a specific framework is really what we want to do

FYI php has a built-in `mail` function aiming for sending emails. But it does not allow setting-up an external SMTP server. That's why having that documentation may be a good addition specifically for PHP.

2025-07-09 09:14 UTC, sc-zenokerr commented
> I'm not sure whether documenting a specific framework is really what we want to do (because maintenance, etc.)
> 
> Also, we should probably advise to use Composer to install the dependency, like so:
> 
> ```shell
> composer require phpmailer/phpmailer
> ```

Done in https://github.com/Scalingo/documentation/pull/2903/commits/fea21e808926555702615d549d8bb1f2269d3d9f

2025-07-09 09:29 UTC, Frzk requested changes
I'd move the instructions to install PHPMailer below the title :-)
The suggestions are broken on GitHub, but should work in the real world.
Everything looks good to me. Thanks again :heart:

2025-07-09 09:29 UTC, Frzk commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +
```suggestion
```

2025-07-09 09:29 UTC, Frzk commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +
```suggestion
 Install `PHPMailer` using `composer` (see [Declaring Dependencies]({% post_url /languages/php/2000-01-01-dependencies %}#declaring-dependencies) for further help):

```shell
composer require phpmailer/phpmailer
```

Then use a script like the following one to send e-mails (notice the use of environment variables):

```

2025-07-09 09:36 UTC, sc-zenokerr commented on src/_posts/languages/php/2000-01-01-sending-emails.md
> +
Nice suggestion

Done in https://github.com/Scalingo/documentation/pull/2903/commits/599a7a1fed357e6a914f72cc40dc8a91f14df3a9

2025-07-09 11:31 UTC, Frzk approved these changes
LGTM, thanks a lot 😀

2025-07-09 11:31 UTC, merged